### ISSUE TITLE
How to use offsets on columns?

### ISSUE THREAD

**Issue by sorokinvj** [bootstrap-styled/v4#117]
Sorry for nub question, but I found zero on the subject in docs. Suppose, I need to offset column by 2 col in large screens, how do I attach offset-lg-2 to <Col>?

**Comment by kopax** [comment]
Hi @sorokinvj, looking at https://github.com/bootstrap-styled/v4/blob/master/src/Col/index.js#L117

It seems that writing `<Col lg={{ offset: 2 }} />` would do it, could you please test it and confirm so I can add some example in our documentation?

**Comment by kopax** [comment]
I've just appended the following example to `<Col />` and `<Row />`:



    You can use `offset`, `size`, `push`, `pull` modifier on any `Col` component:

    ```js
    <Row>
      <Col lg={2} md={{ offset: 4 }}>Hello</Col>
      <Col lg={10} md={2}>World</Col>
    </Row>
    ```

    Left empty to have automatic colums:

    ```js
    <Row>
      <Col>Hello</Col>
      <Col>World</Col>
    </Row>
    ```

**Comment by sorokinvj** [comment]
@kopax Dimitri thanks! Sorry, I forgot completely about this issue,  so haven't closed it.

Thanks for docs!

**Comment by kopax** [comment]
No worries
