### ISSUE TITLE
<Collapse/> not collapsed without <BootstrapProvider />.

### ISSUE THREAD

**Issue by hanoii** [bootstrap-styled/v4#125]
I am trying to use this library without the `<ThemeProvider />`, so that only specific styles are used and trying a simple navbar with the collapse element and it doesn't seem to work, it always shows as open:

```jsx
import React from "react"

import {
  A,
  Form,
  Input,
  Button,
  Navbar,
  Container,
  NavbarBrand,
  NavbarToggler,
  Collapse,
  Nav,
  NavItem,
  NavLink,
} from '@bootstrap-styled/v4';


class Navigation extends React.Component  {
  constructor(props) {
    super(props);
    this.state = { isOpen: false };
  }

  render() {
    const { children, data } = this.props;
    return (
      <Navbar color="faded" light toggleable="lg">
        <NavbarBrand tag={A} to="javascript:;">Brand</NavbarBrand>
        <NavbarToggler onClick={() => this.setState({ isOpen: !this.state.isOpen })} />
        <Collapse navbar isOpen={this.state.isOpen}>
          <Nav navbar className="mr-auto">
            <NavItem>
              <NavLink>Home</NavLink>
            </NavItem>
            <NavItem>
              <NavLink>Friends</NavLink>
            </NavItem>
            <NavItem>
              <NavLink disabled>Disabled</NavLink>
            </NavItem>
          </Nav>
        </Collapse>
      </Navbar>
    )
  }
}

export default Navigation
```

Am I doing something wrong?

**Comment by hanoii** [comment]
See https://q73p7.codesandbox.io/

I remember having styling issues when used like this on #74

**Comment by kopax** [comment]
Hi @hanoii, we generally use a `<BootstrapProvider />` to get all the utilities within it.

- Have you tried with the `<BootstrapProvider />`? 
- Is it working with it? 

If so, it may be similar case than #74.

**Comment by hanoii** [comment]
@kopax thanks but isn't this supposedly a way to go as well? I didn't wanted to use bootstrap provider as I feel that's almost the same as using reactstrap. I feel it takes away the benefit of styled components and it's compartmentalized css-in-js approach.

**Comment by hanoii** [comment]
> Hi @hanoii, we generally use a `<BootstrapProvider />` to get all the utilities within it.
> 
> * Have you tried with the `<BootstrapProvider />`?
> * Is it working with it?
> 
> If so, it may be similar case than #74.

Yes, it works with `<BootstrapProvider />` but it adds a lot more than what I wanted 🤔

**Comment by kopax** [comment]
> Is this a bug as it is on its own?

Yes it is a bug, it should be working. I need to check what styling we have in the bootstrap provider and we don't have without it, and add it to the collapse. 

Then we need to call the same mixins within the collapse so we can use it without the bootstrap provider, I'll have a look asap.
