### ISSUE TITLE
All component variables in one file

### ISSUE THREAD

**Issue by bin4ryio** [bootstrap-styled/v4#130]
# v4

Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/bootstrap-styled/v4/blob/master/.github/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

**Before opening a new issue, you may find an answer in already closed issues**:
https://github.com/bootstrap-styled/v4/issues?q=is%3Aissue+is%3Aclosed

## Issue Type

- [ ] Bug (https://github.com/bootstrap-styled/v4/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [X] Feature (https://github.com/bootstrap-styled/v4/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

Hello! I'm writing a FR in regards on theme variables, so far I am unable to find the default **theme.js**, a sample file will be very helpful for those who wanted to customise.

Also, thanks for sharing such an amazing codebase. This component kit is comparable with a lot of big names, deserve more stars!

## Steps to reproduce

Not applicable.

# Versions

- Node/NPM: Not applicable
- OS: Not applicable
- v4: Latest

**Comment by santaclauze** [comment]
Hey @bin4ryio , the `theme.js` file is located in the `bootstrap-styled` [package](https://github.com/bootstrap-styled/bootstrap-styled/blob/master/src/theme/index.js).
