### ISSUE TITLE
Feature Request: Typescript Types

### ISSUE THREAD

**Issue by aequasi** [bootstrap-styled/v4#138]
## Issue Type

- [ ] [Bug](https://github.com/bootstrap-styled/v4/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [x] [Feature](https://github.com/bootstrap-styled/v4/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

Is there a chance we could get types for this?

**Comment by aequasi** [comment]
Appears that its already in the repo, https://github.com/bootstrap-styled/v4/blob/master/src/index.d.ts, but isn't published?

**Comment by kopax** [comment]
It should be. We use `.npmignore` to exclude files and it is not excluded. I can have a look in september but I do not have experience with typescript. If you know how to help I am only able to accept PR at the moment. Also see https://github.com/bootstrap-styled/bootstrap-styled/issues/83#issuecomment-519218356

**Comment by kopax** [comment]
Closing in profit of https://github.com/bootstrap-styled/bootstrap-styled/issues/83
