### ISSUE TITLE
3.1.1+ builds seem to have a bad file in Cards/tests directory, prevents yarn extracting bundle to cache

### ISSUE THREAD

**Issue by jc99ta** [bootstrap-styled/v4#152]
# v4

Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/bootstrap-styled/v4/blob/master/.github/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

**Before opening a new issue, you may find an answer in already closed issues**:
https://github.com/bootstrap-styled/v4/issues?q=is%3Aissue+is%3Aclosed

## Issue Type

- [X] Bug

## Description

Yarn issue extracting tarball from latest build.  Seems it may have to do with the _ file within Cards/tests directory as this started appearing in 3.1.1

![yarn_log](https://user-images.githubusercontent.com/17990724/64801788-db9a5200-d54e-11e9-88d3-cd821872fb1d.PNG)

This is a screen grab showing the manually downloaded and exploded package. 
![explorer](https://user-images.githubusercontent.com/17990724/64802270-eb666600-d54f-11e9-983f-78f8dc5c690a.PNG)

Issue seems to have started with the 3.1.1 release.

## Steps to reproduce

Attempt to update to the latest release using `yarn upgrade @bootstrap-styled/v4 --latest`

# Versions

- Node/NPM: 6.4.1
- Yarn: 1.17.3
- OS: Windows 10
- v4: 3.1.4 (seems to be broken starting 3.1.1 however)

**Comment by kopax** [comment]
Thanks for reporting this.
