### ISSUE TITLE
[Feature request] Add order-*  to columns as for size and offset

### ISSUE THREAD

**Issue by sorokinvj** [bootstrap-styled/v4#156]
## Feature request

It's better to use `order-*` instead of `push-*`/`pull-*` which is more clear and is working out-of-the box: 

### Proposal

Instead of:

```jsx
<Col className="order-2">Column 1 is ordered 2</Col>
<Col className="order-1">Column 2 is ordered 1</Col>
```

I would improve it like follow:

```jsx
<Col xs={{size: 4, offset: 1, order: 2}} />
```

**Comment by kopax** [comment]
`order-` is working. Can you please post a codesandbox showing how you try to use it.

**Comment by kopax** [comment]
After looking at the mixins [here](https://github.com/bootstrap-styled/css-mixins/blob/master/src/grid-framework.js#L75), it seems clear that the `order-*` is injected.

You can use it with : 

`<Col className="order-1">Column 1</Col>`<Col className="order-1">Column 1</Col>`

If you wan't to add another API to use the `order-*`, please open a feature request.

**Comment by sorokinvj** [comment]
yeah, this is exactly how I end up using it. However, I believe this should be:
```
<Col xs={{size: 4, offset: 1, order: 2}} />
```
> You can use it with :
> 
> ```js-jsx
> <Col className="order-2">Column 1 is ordered 2</Col>
> <Col className="order-1">Column 2 is ordered 1</Col>
> ```

**Comment by kopax** [comment]
This can be implemented, I reopen for tracking, feel free to improve the code base.

**Comment by kopax** [comment]
Added in [v3.2.0](https://github.com/bootstrap-styled/v4/releases/tag/v3.2.0), thanks @toshgoodson.

**Comment by sorokinvj** [comment]
Oh guys, thanks! I wanted to contribute, but life ... Hope to help you guys with something else soon!

**Comment by kopax** [comment]
No worries, opensource is a non profit job often on free time. You are welcome, feel free to star our repo to bring more contributors.
