### ISSUE TITLE
Need advice w/ Nav and it hiding and showing Content

### ISSUE THREAD

**Issue by kvernon** [bootstrap-styled/v4#160]
# v4

Howdy y'all! 

I'm using the latest bootstrap, `"styled-components": "^4.0.0"` and I've gone through the documentation on your site and the documentation over at getbootstrap. Simply put, I don't understand how get this to work, and I'd love some advice; especially since getbootstrap doesn't work with your basics.

So, I have no idea how to get your nav (as a tab) to work in hiding / showing content.

```
// example here is in the React.Component render method
             <Nav tabs>
              <NavItem>
                <NavLink active href="#one">click one</NavLink>
              </NavItem>
              <NavItem>
                <NavLink href="#another" >another</NavLink>
              </NavItem>
            </Nav>
            <Container>
              <OneContainer id='one'/>
              <Container id='another'>
                <div>something else</div>
              </Container>
           </Container>
```

What I trying to understand is how do I get these tabs to hide and show content. Over at https://getbootstrap.com/docs/4.0/components/navs/ they talk about needing to point to the `id` then the magic happens. Here there's no documentation, so I'm trying to understand that flow. Is there a place you all could point me to or a relevant example?

1. I'd love to try out this library (seems fun so far)
2. I'm new at bootstrap and trying to mix these ideas.

Thanks!
Kelly

**Comment by kopax** [comment]
> Over at https://getbootstrap.com/docs/4.0/components/navs/ they talk about needing to point to the `id` then the magic happens. 

This is not getbootstrap, this is an implementation of getbootstrap for react and styled-components.
getbootstrap rely on some external javascript to make the magic happen, we do not rely on `id`, we rely on react and it's `state` management within components.

> Here there's no documentation

https://bootstrap-styled.github.io/v4/#/UI%20Components/Components?id=nav

> What I trying to understand is how do I get these tabs to hide and show content.

I agree that we could have made more example but we try not to make our documentation too big.

Here is an example I've just made for you: 

```jsx
import React from "react";
import ReactDOM from "react-dom";
import {
  Nav,
  NavItem,
  NavLink,
  NavDropdown,
  DropdownToggle,
  DropdownMenu,
  DropdownItem
} from "@bootstrap-styled/v4";
import BootstrapProvider from "@bootstrap-styled/provider";
import cn from "classnames";

class App extends React.Component {
  state = {
    isOpen: false,
    tab: 1
  };

  render() {
    const { isOpen, tab } = this.state;
    return (
      <BootstrapProvider>
        <Nav tabs>
          <NavItem>
            <NavLink
              className="cursor-pointer"
              active={tab === 1}
              onClick={() => this.setState({ tab: 1 })}
            >
              Tab 1
            </NavLink>
          </NavItem>
          <NavDropdown
            isOpen={isOpen}
            toggle={() => this.setState({ isOpen: !isOpen })}
          >
            <DropdownToggle caret nav>
              Dropdown
            </DropdownToggle>
            <DropdownMenu>
              <DropdownItem header>Header</DropdownItem>
              <DropdownItem disabled>Action</DropdownItem>
              <DropdownItem>Another Action</DropdownItem>
              <DropdownItem divider />
              <DropdownItem>Another Action</DropdownItem>
            </DropdownMenu>
          </NavDropdown>
          <NavItem>
            <NavLink
              className="cursor-pointer"
              active={tab === 2}
              onClick={() => this.setState({ tab: 2 })}
            >
              Tab 2
            </NavLink>
          </NavItem>
          <NavItem>
            <NavLink disabled href="javascript:;">
              Disabled
            </NavLink>
          </NavItem>
        </Nav>
        <div className={cn({ "d-none": tab === 1 })}>Hi 1</div>
        <div className={cn({ "d-none": tab === 2 })}>Hi 2</div>
      </BootstrapProvider>
    );
  }
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

Live demo: https://codesandbox.io/embed/loving-architecture-o9h4b

I have used the [`BootstrapProvider`](https://bootstrap-styled.github.io/provider) to inject that inject the [visibility utilities](https://bootstrap-styled.github.io/css-utils/#/Utils/Visibility)

> I'd love to try out this library (seems fun so far)

You're welcome to star our repos and contribute to this project.

**Comment by kvernon** [comment]
Good morning @kopax !

Thanks for helping me understand the flow between the two ideas. The way I took it is, you provide the css foundation, but don't rely on the JavacScript variation, which is where I was pretty lost (again). 

One small change to the example above is that the state is consistently delayed when rendering the classes, so if others are looking at this example, I'm going to alter it just a tad. This way it might help them too!

(pieces updated: removed classname import, changed render to be state tab eqeqeq number AND node
```
import React from "react";
import ReactDOM from "react-dom";
import {
  Nav,
  NavItem,
  NavLink,
  NavDropdown,
  DropdownToggle,
  DropdownMenu,
  DropdownItem
} from "@bootstrap-styled/v4";
import BootstrapProvider from "@bootstrap-styled/provider";

class App extends React.Component {
  state = {
    isOpen: false,
    tab: 1
  };

  render() {
    const { isOpen, tab } = this.state;
    return (
      <BootstrapProvider>
        <Nav tabs>
          <NavItem>
            <NavLink
              className="cursor-pointer"
              active={tab === 1}
              onClick={() => this.setState({ tab: 1 })}
            >
              Tab 1
            </NavLink>
          </NavItem>
          <NavDropdown
            isOpen={isOpen}
            toggle={() => this.setState({ isOpen: !isOpen })}
          >
            <DropdownToggle caret nav>
              Dropdown
            </DropdownToggle>
            <DropdownMenu>
              <DropdownItem header>Header</DropdownItem>
              <DropdownItem disabled>Action</DropdownItem>
              <DropdownItem>Another Action</DropdownItem>
              <DropdownItem divider />
              <DropdownItem>Another Action</DropdownItem>
            </DropdownMenu>
          </NavDropdown>
          <NavItem>
            <NavLink
              className="cursor-pointer"
              active={tab === 2}
              onClick={() => this.setState({ tab: 2 })}
            >
              Tab 2
            </NavLink>
          </NavItem>
          <NavItem>
            <NavLink disabled href="javascript:;">
              Disabled
            </NavLink>
          </NavItem>
        </Nav>
         {tab === 1 && <div>Hi 1</div>}
         {tab === 2 && <div>Hi 2</div>}
      </BootstrapProvider>
    );
  }
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

Again, your help was outstanding, and thank you!
