### ISSUE TITLE
Tooltip arrow color hard coded to #000

### ISSUE THREAD

**Issue by jc99ta** [bootstrap-styled/v4#169]
# v4

Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/bootstrap-styled/v4/blob/master/.github/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

**Before opening a new issue, you may find an answer in already closed issues**:
https://github.com/bootstrap-styled/v4/issues?q=is%3Aissue+is%3Aclosed

## Issue Type

- [x] Bug (https://github.com/bootstrap-styled/v4/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [ ] Feature (https://github.com/bootstrap-styled/v4/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description
Although the property $tooltip-arrow-color is defined for the Tooltip component, overriding this theme value has no effect.

The arrow color is hard coded in the styling to #000
![tooltip](https://user-images.githubusercontent.com/17990724/68795003-afb25000-0615-11ea-9750-d91d7f7e5bc4.PNG)

## Steps to reproduce

(Add link to a demo on https://jsfiddle.net or similar if possible)

# Versions

- Node/NPM: 10.15.2/6.12.1
- OS: Windows
- v4: 3.2.0

**Comment by kopax** [comment]
Hi and thanks, could you submit PR ?

**Comment by kopax** [comment]
Thanks for fixing, travis will release a fix in the next minutes.

**Comment by jc99ta** [comment]
Will do, thanks!

**Comment by kopax** [comment]
It's broken, I will just update a few deps and repair. https://www.travis-ci.org/bootstrap-styled/v4/jobs/611589056

**Comment by kopax** [comment]
New release in progress https://www.travis-ci.org/bootstrap-styled/v4/jobs/611615043. I've also fixed the  documentaton so we don't load all the components on one page ^^,

**Comment by kopax** [comment]
Closing, feel free to reopen
