### ISSUE TITLE
.btn-dark is missing

### ISSUE THREAD

**Issue by nojaf** [bootstrap-styled/v4#183]
# v4

Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/bootstrap-styled/v4/blob/master/.github/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

**Before opening a new issue, you may find an answer in already closed issues**:
https://github.com/bootstrap-styled/v4/issues?q=is%3Aissue+is%3Aclosed

## Issue Type

- [ ] Bug (https://github.com/bootstrap-styled/v4/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [X] Feature (https://github.com/bootstrap-styled/v4/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

`.btn-dark` is missing, see https://getbootstrap.com/docs/4.4/components/buttons/

## Steps to reproduce

```jsx
<Button color='dark'>foo<Button>
```

# Versions

- Node/NPM: 12.x
- OS: Windows
- v4: 3.3.0

**Comment by kopax** [comment]
Hi @nojaf, please read this comment:

- https://github.com/bootstrap-styled/v4/issues/178#issuecomment-565710887

And original issue:

- https://github.com/bootstrap-styled/v4/issues/92

You are welcome for PR fix #92, or you can just do like this PR with the white color (takes 30sec): https://github.com/bootstrap-styled/v4/pull/179

You can still use `className` without any change.

Closing, please use the original issue to continue this discussion.
