### ISSUE TITLE
Question: How do you change the background colour for the entire site/BootstrapProvider?

### ISSUE THREAD

**Issue by VED-StuartMorris** [bootstrap-styled/v4#207]
Hello,

This is more of a question around functionality that is not clear within the documentation. 

How does one change the background for the entire web app? As an example I can go to here: https://bootstrap-styled.github.io/v4/, within the Introduction you can obviously change the code and see the changes refresh.

Simply adding ` '$bg-color': 'black',` to the theme will only change the background outside of the Provider.

I've set up a new project following the instructions and the same occurs. I simply add a `<BootstrapProvider>` and pass in a theme with this value. What appears to happen is a UtilityProvider is added as the next layer which has a background color of white. So how could you change that when it is injected in?

I suppose I could just create a Styled-components version of the BootstrapProvider with some styles associated to it and that might work, but thought this might be something already available.

Thanks

**Comment by VED-StuartMorris** [comment]
I was being stupid and attached the theme with {{}} instead of just {} which made it filter down. Strange because it was working for setting a button to success just not the background color variable.

**Comment by kopax** [comment]
You are welcome, and thanks for using our repo, if you like it, be welcome to star our repo !
