### ISSUE TITLE
Question: Global styles of bootstrap 4

### ISSUE THREAD

**Issue by umakantp** [bootstrap-styled/v4#215]
Hi Team,

I  know this is NOT the right place to ask a questions (may be Stackoverflow). I'm badly stuck and have been searching documentation and other sources for the answer. Nothing helped, Hence decided to ask authors/community directly.

I would like to know form where and how to get all the global styles of bootstrap using @bootstrap-styled/v4 ? May be with the help of @bootstrap-styled/provider ?

Bootstrap adds some global css like example reset css. I see that missing plus not able to find in the docs. Side effect of it says example my projects <body> has margin (user agent styles) since such styles are missing.

Can someone help please?

**Comment by kopax-polyconseil** [comment]
You need to use the UtilityProvider which is provided in bootstrap provider, it won't be global, it will scoped to your react app. if you want to use them as globalStyle, you can use the css-utils or css-mixins utility directly into your inject global. See appropriate documentation and welcome if you have further question.

**Comment by umakantp** [comment]
Thanks for the quick reply. What you are proposing is to create global styles with the help of those utilities?

**Comment by kopax-polyconseil** [comment]
Yes, this is why we separate all the utils, so you can assemble what you need, take just the utilities, or the utilities scoped in a utility provider or within a bootstrap provider etc...

Code source is open source, so if you have a check at those utils, or just console.log the return, you'll see that you'll have the css generated. I am not sure that you can use the mixins with `injectGlobal`, as they are supposed to be in the scope of an existing component and are prefixed with `&`, but you can use them in global style as a mixin of a global style.

**Comment by umakantp** [comment]
This would work for me. I think this should be covered in the docs may be? Could be of help to some one like me. I'm closing the issue. Thank you.

**Comment by kopax-polyconseil** [comment]
You are welcome @umakantp. I think this is already documented, and you are welcome to improve the documentation and submit improvement at any time, I'll review.  Have a good weekend!
