### ISSUE TITLE
[Maj Cards] Update CardGroup css to respect Bootstrap 4.1.3

### ISSUE THREAD

**Issue by kopax** [bootstrap-styled/v4#40]
# v4

During the upgrade of Grid mixins, we had to update the variables:

```js
  detectedUnit = detectUnit(v['$grid-gutter-width']);
  v['$card-group-margin'] = u['$card-group-margin'] || (rmUnit(v['$grid-gutter-width'], detectedUnit) / 2) + detectedUnit;
  v['$card-deck-margin'] = u['$card-deck-margin'] || v['$card-group-margin'];
```

- Added variable `$card-group-margin`, `$grid-gutter-width`, remove `$grid-gutter-widths` `$grid-gutter-width-base`

In bootstrap v4.1.3 they have added `$card-group-margin` variables which is used by Card group.

## Related issues/pull

- https://github.com/bootstrap-styled/bootstrap-styled/pull/57
- https://github.com/bootstrap-styled/css-mixins/pull/18
- https://github.com/bootstrap-styled/css-mixins/issues/16
- https://github.com/bootstrap-styled/bootstrap-styled/issues/40

## Issue Type

- [x] Bug

## Description

See usage at: https://github.com/twbs/bootstrap/blob/v4-dev/scss/_card.scss#L179

The `<CardGroup />` and card mixins seems to differ from current `card.js` mixins, this issue consist of updating to Bootstrap v4.1.3 our cards.

Considering the amount of change, I think it is easier and safer to start over with the latest sources and drop the current one.

**Comment by santaclauze** [comment]
Should we close this?

**Comment by kopax** [comment]
No, our cards still differ from the latest version. The priority is low as the old one still work.
