### ISSUE TITLE
Find why dropdown are wrongly positionned on codesandbox

### ISSUE THREAD

**Issue by kopax** [bootstrap-styled/v4#70]
# Dropdown have weird position on codesandbox.

The CSS for the dropdown display a border while it should not:

## Issue Type

- [x] [Bug](https://github.com/bootstrap-styled/v4/blob/master/.github/CONTRIBUTING.md#bug-reports)

## Description

https://codesandbox.io/s/l530l0vz6m

The positioning on the codesandbox is wrong.

**Comment by santaclauze** [comment]
That has been fixed already
