### ISSUE TITLE
[Bug] Input border width

### ISSUE THREAD

**Issue by jayakornk** [bootstrap-styled/v4#82]
# v4: Input / Button border-width

## Issue Type

- [x] [Bug](https://github.com/bootstrap-styled/v4/blob/master/.github/CONTRIBUTING.md#bug-reports)

## Description

https://bootstrap-styled.github.io/v4/#/UI%20Components/Form

`$input-btn-border-width` effects both `<Button />` and `<Input />` even when `$border-width` is set.

**Theme**
![image](https://user-images.githubusercontent.com/46859480/52131088-7ef8bf80-266e-11e9-9ca4-2fbc14586c92.png)

**Result**
![image](https://user-images.githubusercontent.com/46859480/52130999-4bb63080-266e-11e9-8f86-adbd5cc8ee10.png)

## Steps to reproduce

Try set `$input-btn-border-width` and `$border-width` with different value.

# Versions

- Node/NPM: **Node** v11.7.0 / **NPM** v6.6.0
- OS: **macOS Mojave v10.14.2**
- v4: **2.0.20**

**Comment by kopax** [comment]
Hi @jayakornk can we get a reproduction or at least the context.

How/where do you modify the theme?

**Comment by santaclauze** [comment]
@jayakornk , yup I identified the problem, the fix is on it's way.
