### ISSUE TITLE
[Documentation] <Tooltip /> and <Dropdown /> are not rendering proper css in development documentation

### ISSUE THREAD

**Issue by kopax** [bootstrap-styled/v4#99]
## Issue Type

- [x] Documentation Bug (https://github.com/bootstrap-styled/v4/blob/master/.github/CONTRIBUTING.md#bug-reports)

## Description

The `<Tooltip />` are different looking when running the documentation in `development` and `production`

## Steps to reproduce

Development:

![image](https://user-images.githubusercontent.com/1866564/54083597-221cb300-4358-11e9-96c4-8c227e53702f.png)

Production:

![image](https://user-images.githubusercontent.com/1866564/54083607-3f518180-4358-11e9-89a5-1d9a2a7b12bf.png)

# References

- https://github.com/bootstrap-styled/v4/pull/97#issuecomment-471273923
- v4: v3.0.5

**Comment by ajmadsen** [comment]
I noticed this also affects Dropdown in development:
<img width="299" alt="Screen Shot 2019-03-10 at 3 21 45 AM" src="https://user-images.githubusercontent.com/4017830/54083655-c1539300-42e3-11e9-8af9-9abb5f67a835.png">

**Comment by santaclauze** [comment]
@kopax , @ajmadsen , for some reason the css was not applied correctly, I had to add both components to `global` in the `styleguide/setup.js` to fix this.

Closing as it should be fixed once merge is complete.
